import os
import pickle
import numpy as np
import streamlit as st

# --- Load the trained model -------------------------------------------------
# Resolve the path relative to this script's own location, not the current
# working directory. This is required for Streamlit Community Cloud, which
# does not guarantee the working directory matches the repo root.
MODEL_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "breast_cancer_model.pkl")


@st.cache_resource
def load_model():
    with open(MODEL_PATH, "rb") as f:
        return pickle.load(f)


try:
    model = load_model()
except FileNotFoundError:
    st.error(
        f"Could not find `breast_cancer_model.pkl` at:\n\n{MODEL_PATH}\n\n"
        "Make sure this file is committed to your GitHub repo in the same "
        "folder as app.py."
    )
    st.stop()
except Exception as e:
    st.error(f"Failed to load the model: {e}")
    st.stop()

# --- Page setup ---------------------------------------------------------
st.set_page_config(page_title="Breast Cancer Diagnosis", page_icon="🩺")
st.title("🩺 Breast Cancer Diagnosis Predictor")
st.write(
    "This tool uses a Random Forest model trained on the Wisconsin Breast Cancer "
    "dataset to predict whether a tumor is **benign** or **malignant** based on "
    "cell nuclei measurements."
)
st.warning("⚠️ For educational purposes only. Not for clinical or diagnostic use.")

# --- Inputs ---------------------------------------------------------------
st.header("Enter Tumor Measurements")
col1, col2 = st.columns(2)

with col1:
    radius_mean = st.number_input("Radius Mean", min_value=0.0, value=14.0, step=0.1)
    perimeter_mean = st.number_input("Perimeter Mean", min_value=0.0, value=90.0, step=0.1)
    area_mean = st.number_input("Area Mean", min_value=0.0, value=650.0, step=1.0)
    compactness_mean = st.number_input(
        "Compactness Mean", min_value=0.0, value=0.1, step=0.01, format="%.4f"
    )
    concavity_mean = st.number_input(
        "Concavity Mean", min_value=0.0, value=0.1, step=0.01, format="%.4f"
    )

with col2:
    concave_points_mean = st.number_input(
        "Concave Points Mean", min_value=0.0, value=0.05, step=0.01, format="%.4f"
    )
    radius_se = st.number_input("Radius SE", min_value=0.0, value=0.4, step=0.01, format="%.4f")
    area_se = st.number_input("Area SE", min_value=0.0, value=40.0, step=1.0)
    radius_worst = st.number_input("Radius Worst", min_value=0.0, value=16.0, step=0.1)
    perimeter_worst = st.number_input("Perimeter Worst", min_value=0.0, value=105.0, step=0.1)
    compactness_worst = st.number_input(
        "Compactness Worst", min_value=0.0, value=0.25, step=0.01, format="%.4f"
    )

# --- Prediction -------------------------------------------------------------
if st.button("Predict Diagnosis", type="primary"):
    # Order must match model.feature_names_in_ from training:
    # ['radius_mean', 'perimeter_mean', 'area_mean', 'compactness_mean',
    #  'concavity_mean', 'concave points_mean', 'radius_se', 'area_se',
    #  'radius_worst', 'perimeter_worst', 'compactness_worst']
    features = np.array(
        [
            [
                radius_mean,
                perimeter_mean,
                area_mean,
                compactness_mean,
                concavity_mean,
                concave_points_mean,
                radius_se,
                area_se,
                radius_worst,
                perimeter_worst,
                compactness_worst,
            ]
        ]
    )

    prediction = model.predict(features)[0]
    probability = model.predict_proba(features)[0]

    # Look up class indices explicitly instead of assuming order [0, 1]
    classes = list(model.classes_)
    benign_idx = classes.index(0)
    malignant_idx = classes.index(1)

    st.header("Result")
    if prediction == 1:
        st.error(f"⚠️ Predicted: **Malignant** (confidence: {probability[malignant_idx] * 100:.1f}%)")
    else:
        st.success(f"✅ Predicted: **Benign** (confidence: {probability[benign_idx] * 100:.1f}%)")

    st.caption(
        "This prediction is generated by a machine learning model trained on the "
        "Wisconsin Breast Cancer dataset and should not be used as a substitute "
        "for professional medical advice."
    )

st.divider()
st.caption("Model: Random Forest (tuned via GridSearchCV) | Accuracy: 93% | AUC: 0.96")
